spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres?currentSchema=flyway_accelerator
    username: postgres
    password: postgres

  flyway:
    user: postgres
    password: postgres
    schemas: flyway_accelerator
    url: jdbc:postgresql://localhost:5432/postgres
    locations: classpath:db/migration
    placeholders:
      defaultUser: Admin
    repeatable-sql-migration-prefix: Repeatable
