spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres?currentSchema=flyway_accelerator
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      uri: mongodb://docker:mongopw@localhost:49153/test?authSource=admin
  flyway:
    user: postgres
    password: postgres
    schemas: flyway_accelerator
    url: jdbc:postgresql://localhost:5432/postgres
    locations: classpath:db/migration
    placeholders:
      defaultUser: Admin
    repeatable-sql-migration-prefix: Repeatable
logging:
  level:
    io:
      reflectoring: DEBUG
    org:
      springframework:
        web: INFO
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
    reactor:
      netty:
        http:
          client: DEBUG